import type { User, Team, Chat, Debate, Bet, HotTake, HotTakeComment, DebateArgument } from './types';
import { ALL_TEAMS } from './teams-data';

export const TEAMS: Team[] = ALL_TEAMS;

export const USERS: User[] = [
  {
    id: 'me',
    username: 'jhayes23',
    displayName: 'Jordan Hayes',
    avatar: '🤙',
    bio: 'Born & raised in the Bronx. Bleed blue. If you talk crazy about the Giants or Knicks, I\'m ready.',
    fanTeams: [
      { team: TEAMS[0], rank: 1, fandomLevel: 'diehard' },
      { team: TEAMS[1], rank: 2, fandomLevel: 'diehard' },
      { team: TEAMS[2], rank: 3, fandomLevel: 'supporter' },
      { team: TEAMS[3], rank: 4, fandomLevel: 'fair-weather' },
    ],
    stats: {
      debatesWon: 7,
      debatesLost: 3,
      debatesDrew: 1,
      betsWon: 5,
      betsLost: 2,
      betsPending: 2,
      hotTakesPosted: 14,
      hotTakeReactions: 89,
    },
    followingIds: ['marcus', 'deshawn', 'sofia', 'tre'],
    followerIds: ['marcus', 'deshawn', 'sofia', 'tre'],
    groupIds: ['council', 'nyc-ball', 'nfc-east'],
  },
  {
    id: 'marcus',
    username: 'mwebb_chief',
    displayName: 'Marcus Webb',
    avatar: '👑',
    bio: 'Chiefs Kingdom forever. Laker Nation. Don\'t @ me.',
    fanTeams: [
      { team: TEAMS[4], rank: 1, fandomLevel: 'diehard' },
      { team: TEAMS[5], rank: 2, fandomLevel: 'supporter' },
    ],
    stats: {
      debatesWon: 4,
      debatesLost: 6,
      debatesDrew: 2,
      betsWon: 3,
      betsLost: 4,
      betsPending: 1,
      hotTakesPosted: 22,
      hotTakeReactions: 134,
    },
    followingIds: ['me', 'deshawn', 'sofia', 'tre'],
    followerIds: ['me', 'deshawn', 'sofia', 'tre'],
    groupIds: ['council', 'nyc-ball'],
  },
  {
    id: 'deshawn',
    username: 'd_payne_eagles',
    displayName: 'DeShawn Payne',
    avatar: '🦅',
    bio: 'E-A-G-L-E-S. Trust the process. Ring the bell.',
    fanTeams: [
      { team: TEAMS[6], rank: 1, fandomLevel: 'diehard' },
      { team: TEAMS[7], rank: 2, fandomLevel: 'supporter' },
    ],
    stats: {
      debatesWon: 9,
      debatesLost: 2,
      debatesDrew: 0,
      betsWon: 6,
      betsLost: 1,
      betsPending: 0,
      hotTakesPosted: 18,
      hotTakeReactions: 211,
    },
    followingIds: ['me', 'marcus', 'sofia', 'tre'],
    followerIds: ['me', 'marcus', 'sofia', 'tre'],
    groupIds: ['council', 'nfc-east'],
  },
  {
    id: 'sofia',
    username: 'sofia_warriors',
    displayName: 'Sofia Rivera',
    avatar: '💪',
    bio: 'Bay Area born. Warriors until I die. 49ers faithful.',
    fanTeams: [
      { team: TEAMS[8], rank: 1, fandomLevel: 'diehard' },
      { team: TEAMS[9], rank: 2, fandomLevel: 'fair-weather' },
    ],
    stats: {
      debatesWon: 5,
      debatesLost: 4,
      debatesDrew: 3,
      betsWon: 4,
      betsLost: 3,
      betsPending: 1,
      hotTakesPosted: 9,
      hotTakeReactions: 67,
    },
    followingIds: ['me', 'marcus', 'deshawn', 'tre'],
    followerIds: ['me', 'marcus', 'deshawn', 'tre'],
    groupIds: ['council', 'nyc-ball'],
  },
  {
    id: 'tre',
    username: 'trewill_stars',
    displayName: 'Tre Williams',
    avatar: '⭐',
    bio: 'America\'s Team. If you know, you know.',
    fanTeams: [
      { team: TEAMS[10], rank: 1, fandomLevel: 'diehard' },
      { team: TEAMS[11], rank: 2, fandomLevel: 'casual' },
    ],
    stats: {
      debatesWon: 3,
      debatesLost: 8,
      debatesDrew: 1,
      betsWon: 2,
      betsLost: 5,
      betsPending: 2,
      hotTakesPosted: 31,
      hotTakeReactions: 178,
    },
    followingIds: ['me', 'marcus', 'deshawn', 'sofia'],
    followerIds: ['me', 'marcus', 'deshawn', 'sofia'],
    groupIds: ['council', 'nfc-east'],
  },
];

export const ME = USERS[0];

export const CHATS: Chat[] = [
  {
    id: 'council',
    name: 'The Council',
    emoji: '🏆',
    memberIds: ['me', 'marcus', 'deshawn', 'sofia', 'tre'],
    teamIds: ['giants', 'chiefs', 'eagles', 'warriors', 'cowboys'],
    messages: [
      {
        id: 'm1',
        chatId: 'council',
        userId: 'marcus',
        content: 'Mahomes is the greatest QB of this generation, no debate needed.',
        timestamp: '2026-05-12T09:00:00Z',
        tag: 'hot-take',
        reactions: [
          { emoji: '🔥', userIds: ['sofia', 'tre'] },
          { emoji: '🧢', userIds: ['me', 'deshawn'] },
        ],
      },
      {
        id: 'm2',
        chatId: 'council',
        userId: 'me',
        content: 'Bro has the easiest schedule in the league every year and a top 3 OL. Let\'s not.',
        timestamp: '2026-05-12T09:03:00Z',
        reactions: [
          { emoji: '💯', userIds: ['deshawn'] },
        ],
      },
      {
        id: 'm3',
        chatId: 'council',
        userId: 'deshawn',
        content: 'LeBron would\'ve won 7 rings with the resources Jordan had. MJ is overrated.',
        timestamp: '2026-05-12T09:15:00Z',
        tag: 'debate',
        reactions: [
          { emoji: '😭', userIds: ['me', 'marcus', 'tre'] },
          { emoji: '💯', userIds: ['sofia'] },
        ],
      },
      {
        id: 'm4',
        chatId: 'council',
        userId: 'tre',
        content: 'Cowboys are winning the NFC this year. I\'ll bet anyone on that.',
        timestamp: '2026-05-12T10:00:00Z',
        tag: 'bet',
        reactions: [
          { emoji: '😂', userIds: ['me', 'deshawn', 'sofia', 'marcus'] },
        ],
      },
      {
        id: 'm5',
        chatId: 'council',
        userId: 'sofia',
        content: 'The Knicks are only relevant because they\'re in New York. Remove the market and nobody talks about them.',
        timestamp: '2026-05-12T10:30:00Z',
        tag: 'hot-take',
        reactions: [
          { emoji: '🔥', userIds: ['marcus', 'deshawn', 'tre'] },
          { emoji: '🤬', userIds: ['me'] },
        ],
      },
      {
        id: 'm6',
        chatId: 'council',
        userId: 'me',
        content: 'The Knicks are a top 5 most valuable franchise in ALL of sports. Respectfully disagree.',
        timestamp: '2026-05-12T10:33:00Z',
        reactions: [
          { emoji: '💯', userIds: ['marcus'] },
        ],
      },
      {
        id: 'm7',
        chatId: 'council',
        userId: 'marcus',
        content: 'Giants beat the Eagles in Week 14. Put something on it, DeShawn.',
        timestamp: '2026-05-12T11:00:00Z',
        tag: 'bet',
        reactions: [
          { emoji: '👀', userIds: ['me', 'sofia', 'tre'] },
          { emoji: '🤝', userIds: ['deshawn'] },
        ],
      },
    ],
  },
  {
    id: 'nyc-ball',
    name: 'NYC Ball 🗽',
    emoji: '🗽',
    memberIds: ['me', 'sofia', 'marcus'],
    teamIds: ['giants', 'knicks', 'yankees'],
    messages: [
      {
        id: 'n1',
        chatId: 'nyc-ball',
        userId: 'sofia',
        content: 'The Yankees are going to the Series this year. Mark it.',
        timestamp: '2026-05-11T18:00:00Z',
        tag: 'hot-take',
        reactions: [
          { emoji: '🔥', userIds: ['me'] },
          { emoji: '🙏', userIds: ['me'] },
        ],
      },
      {
        id: 'n2',
        chatId: 'nyc-ball',
        userId: 'me',
        content: 'Finally someone with sense in this chat',
        timestamp: '2026-05-11T18:02:00Z',
        reactions: [{ emoji: '😂', userIds: ['sofia', 'marcus'] }],
      },
      {
        id: 'n3',
        chatId: 'nyc-ball',
        userId: 'marcus',
        content: 'Knicks or Lakers in the Finals this year. Bet.',
        timestamp: '2026-05-11T19:00:00Z',
        tag: 'bet',
        reactions: [
          { emoji: '🤝', userIds: ['me'] },
          { emoji: '😂', userIds: ['sofia'] },
        ],
      },
    ],
  },
  {
    id: 'nfc-east',
    name: 'NFC East Wars',
    emoji: '🏈',
    memberIds: ['me', 'deshawn', 'tre'],
    teamIds: ['giants', 'eagles', 'cowboys'],
    messages: [
      {
        id: 'e1',
        chatId: 'nfc-east',
        userId: 'deshawn',
        content: 'Eagles are the class of the NFC. Division is over before it started.',
        timestamp: '2026-05-10T14:00:00Z',
        tag: 'hot-take',
        reactions: [
          { emoji: '🔥', userIds: ['deshawn'] },
          { emoji: '🧢', userIds: ['me', 'tre'] },
        ],
      },
      {
        id: 'e2',
        chatId: 'nfc-east',
        userId: 'tre',
        content: 'Cowboys own this division historically. One good season doesn\'t change legacy.',
        timestamp: '2026-05-10T14:15:00Z',
        tag: 'debate',
        reactions: [
          { emoji: '😂', userIds: ['deshawn', 'me'] },
        ],
      },
      {
        id: 'e3',
        chatId: 'nfc-east',
        userId: 'me',
        content: 'Giants sweep both of yall this year. Remember this message.',
        timestamp: '2026-05-10T14:30:00Z',
        tag: 'bet',
        reactions: [
          { emoji: '😭', userIds: ['deshawn', 'tre'] },
          { emoji: '🤝', userIds: ['deshawn'] },
        ],
      },
    ],
  },
];

export const DEBATES: Debate[] = [
  {
    id: 'd1',
    chatId: 'council',
    chatName: 'The Council 🏆',
    claim: 'LeBron would\'ve won 7 rings with the resources Jordan had. MJ is overrated.',
    side1UserIds: ['deshawn', 'sofia'],
    side2UserIds: ['me', 'marcus', 'tre'],
    side1Label: 'Team LeBron',
    side2Label: 'Team MJ',
    arguments: [
      {
        id: 'da1',
        userId: 'deshawn',
        side: 'side1',
        content: 'LeBron carried a Cavs team with zero help to the Finals multiple times. Jordan had Pippen every ring.',
        timestamp: '2026-05-12T09:16:00Z',
        reactions: [{ emoji: '💯', userIds: ['sofia'] }],
      },
      {
        id: 'da2',
        userId: 'me',
        side: 'side2',
        content: 'Pippen was elite but Jordan made him. MJ averaged 35 in the playoffs. LeBron coasted in the East for years.',
        timestamp: '2026-05-12T09:20:00Z',
        reactions: [{ emoji: '🔥', userIds: ['marcus', 'tre'] }],
      },
      {
        id: 'da3',
        userId: 'sofia',
        side: 'side1',
        content: 'MJ never faced a prime Magic, Bird, or Shaq. The competition was softer.',
        timestamp: '2026-05-12T09:25:00Z',
        reactions: [{ emoji: '🤔', userIds: ['me'] }],
      },
      {
        id: 'da4',
        userId: 'marcus',
        side: 'side2',
        content: 'MJ went 6 for 6 in Finals, never needed a Game 7. That\'s cold-blooded greatness.',
        timestamp: '2026-05-12T09:30:00Z',
        reactions: [{ emoji: '💀', userIds: ['deshawn'] }],
      },
    ] as DebateArgument[],
    votes: [
      { userId: 'sofia', choice: 'side1' },
      { userId: 'marcus', choice: 'side2' },
      { userId: 'tre', choice: 'side2' },
    ],
    status: 'active',
    teamIds: [],
    createdAt: '2026-05-12T09:15:00Z',
    isPublic: true,
  },
  {
    id: 'd2',
    chatId: 'nfc-east',
    chatName: 'NFC East Wars 🏈',
    claim: 'Cowboys own this division historically. One good Eagles season doesn\'t change legacy.',
    side1UserIds: ['tre'],
    side2UserIds: ['deshawn', 'me'],
    side1Label: 'America\'s Team',
    side2Label: 'Fly Eagles Fly',
    arguments: [
      {
        id: 'db1',
        userId: 'tre',
        side: 'side1',
        content: '5 Super Bowls, America\'s Team for a reason. Eagles have one lucky ring.',
        timestamp: '2026-05-10T14:16:00Z',
        reactions: [{ emoji: '😂', userIds: ['deshawn', 'me'] }],
      },
      {
        id: 'db2',
        userId: 'deshawn',
        side: 'side2',
        content: 'Last Super Bowl in the NFC East? Eagles. Cowboys haven\'t won in 30 years. Legacy is a cope.',
        timestamp: '2026-05-10T14:20:00Z',
        reactions: [{ emoji: '🔥', userIds: ['me'] }],
      },
    ] as DebateArgument[],
    votes: [
      { userId: 'me', choice: 'side2' },
      { userId: 'deshawn', choice: 'side2' },
    ],
    status: 'active',
    teamIds: ['eagles', 'cowboys'],
    createdAt: '2026-05-10T14:15:00Z',
    isPublic: true,
  },
  {
    id: 'd3',
    chatId: 'council',
    chatName: 'The Council 🏆',
    claim: 'Mahomes has the easiest schedule in the league. His stats are inflated.',
    side1UserIds: ['me', 'deshawn'],
    side2UserIds: ['marcus', 'sofia'],
    side1Label: 'Schedule Padding',
    side2Label: 'GOAT Behavior',
    arguments: [
      {
        id: 'dc1',
        userId: 'me',
        side: 'side1',
        content: 'Check the SOS rankings — Chiefs face bottom-5 defenses every year. Easy to look good.',
        timestamp: '2026-05-08T10:05:00Z',
        reactions: [{ emoji: '💯', userIds: ['deshawn'] }],
      },
      {
        id: 'dc2',
        userId: 'marcus',
        side: 'side2',
        content: 'You don\'t drop 35+ on bad defenses only. He shreds everyone. Brady didn\'t get this hate.',
        timestamp: '2026-05-08T10:15:00Z',
        reactions: [{ emoji: '🔥', userIds: ['sofia'] }],
      },
      {
        id: 'dc3',
        userId: 'deshawn',
        side: 'side1',
        content: 'Brady had Belichick. Mahomes has Reid. Neither did it alone. Stop the GOAT talk.',
        timestamp: '2026-05-08T10:30:00Z',
        reactions: [{ emoji: '🤔', userIds: ['marcus'] }],
      },
    ] as DebateArgument[],
    votes: [
      { userId: 'deshawn', choice: 'side1' },
      { userId: 'sofia', choice: 'side2' },
      { userId: 'tre', choice: 'side1' },
      { userId: 'marcus', choice: 'side2' },
    ],
    status: 'resolved',
    resolution: 'side1',
    teamIds: ['chiefs'],
    createdAt: '2026-05-08T10:00:00Z',
    resolvedAt: '2026-05-09T14:00:00Z',
  },
];

export const BETS: Bet[] = [
  {
    id: 'b1',
    chatId: 'council',
    chatName: 'The Council 🏆',
    claim: 'Giants beat the Eagles in Week 14',
    participantIds: ['marcus', 'deshawn'],
    side1Ids: ['marcus'],
    side2Ids: ['deshawn'],
    side1Label: 'Giants Win',
    side2Label: 'Eagles Win',
    stakes: 'Loser buys game-day snacks for the whole group',
    status: 'active',
    teamIds: ['giants', 'eagles'],
    createdAt: '2026-05-12T11:00:00Z',
  },
  {
    id: 'b2',
    chatId: 'council',
    chatName: 'The Council 🏆',
    claim: 'Cowboys are winning the NFC this year',
    participantIds: ['tre', 'me'],
    side1Ids: ['tre'],
    side2Ids: ['me'],
    side1Label: 'Cowboys In',
    side2Label: 'No Way',
    stakes: 'Winner picks the watch party playlist all season',
    status: 'active',
    teamIds: ['cowboys'],
    createdAt: '2026-05-12T10:00:00Z',
    isPublic: true,
  },
  {
    id: 'b3',
    chatId: 'nyc-ball',
    chatName: 'NYC Ball 🗽',
    claim: 'Knicks or Lakers make the Finals this year',
    participantIds: ['marcus', 'me'],
    side1Ids: ['marcus'],
    side2Ids: ['me'],
    side1Label: 'Lakers/Knicks',
    side2Label: 'Neither',
    stakes: 'Loser wears the winner\'s jersey to the next game night',
    status: 'awaiting-resolution',
    proposal: {
      proposedBy: 'marcus',
      winnerId: 'marcus',
      isPush: false,
      agreements: ['marcus'],
      disputes: [],
    },
    teamIds: ['knicks', 'lakers'],
    createdAt: '2026-05-11T19:00:00Z',
    isPublic: true,
  },
  {
    id: 'b4',
    chatId: 'nfc-east',
    chatName: 'NFC East Wars 🏈',
    claim: 'Giants sweep both Eagles and Cowboys this year',
    participantIds: ['me', 'deshawn'],
    status: 'resolved',
    winnerId: 'me',
    teamIds: ['giants', 'eagles', 'cowboys'],
    createdAt: '2026-04-28T14:30:00Z',
    resolvedAt: '2026-05-05T18:00:00Z',
  },
];

export const HOT_TAKES: HotTake[] = [
  {
    id: 'ht1',
    chatId: 'council',
    chatName: 'The Council 🏆',
    content: 'Mahomes is the greatest QB of this generation, no debate needed.',
    authorId: 'marcus',
    reactions: [
      { emoji: '🔥', userIds: ['sofia', 'tre'] },
      { emoji: '❄️', userIds: ['me', 'deshawn'] },
    ],
    teamIds: ['chiefs'],
    createdAt: '2026-05-12T09:00:00Z',
    isPublic: true,
    comments: [
      { id: 'c1a', userId: 'deshawn', content: 'Nah @mwebb_chief you\'re trolling yourself with this one', timestamp: '2026-05-12T09:05:00Z' },
      { id: 'c1b', userId: 'sofia', content: 'Two Super Bowls before 30. The numbers don\'t lie 🔥', timestamp: '2026-05-12T09:08:00Z' },
    ] as HotTakeComment[],
  },
  {
    id: 'ht2',
    chatId: 'council',
    chatName: 'The Council 🏆',
    content: 'The Knicks are only relevant because they\'re in New York. Remove the market and nobody talks about them.',
    authorId: 'sofia',
    reactions: [
      { emoji: '🔥', userIds: ['marcus', 'deshawn', 'tre'] },
      { emoji: '❄️', userIds: ['me'] },
    ],
    teamIds: ['knicks'],
    createdAt: '2026-05-12T10:30:00Z',
    isPublic: true,
    comments: [
      { id: 'c2a', userId: 'me', content: '@s_flores_nyc this is a CRIME and you know it', timestamp: '2026-05-12T10:35:00Z' },
    ] as HotTakeComment[],
  },
  {
    id: 'ht3',
    chatId: 'nyc-ball',
    chatName: 'NYC Ball 🗽',
    content: 'The Yankees are going to the Series this year. Mark it.',
    authorId: 'sofia',
    reactions: [
      { emoji: '🔥', userIds: ['me'] },
      { emoji: '❄️', userIds: ['marcus'] },
    ],
    teamIds: ['yankees'],
    createdAt: '2026-05-11T18:00:00Z',
    isPublic: false,
    comments: [] as HotTakeComment[],
  },
  {
    id: 'ht4',
    chatId: 'nfc-east',
    chatName: 'NFC East Wars 🏈',
    content: 'Eagles are the class of the NFC. Division is over before it started.',
    authorId: 'deshawn',
    reactions: [
      { emoji: '🔥', userIds: ['deshawn'] },
      { emoji: '❄️', userIds: ['me', 'tre'] },
    ],
    teamIds: ['eagles'],
    createdAt: '2026-05-10T14:00:00Z',
    isPublic: true,
    comments: [] as HotTakeComment[],
  },
  {
    id: 'ht5',
    chatId: 'council',
    chatName: 'The Council 🏆',
    content: 'Tom Brady had the most system-aided dynasty in NFL history. Belichick was the GOAT, not Brady.',
    authorId: 'me',
    reactions: [
      { emoji: '🔥', userIds: ['deshawn', 'tre'] },
      { emoji: '❄️', userIds: ['marcus'] },
    ],
    teamIds: [],
    createdAt: '2026-05-09T20:00:00Z',
    isPublic: true,
    comments: [
      { id: 'c5a', userId: 'marcus', content: 'Brady > system, this is cope @jhayes23', timestamp: '2026-05-09T20:10:00Z' },
      { id: 'c5b', userId: 'tre', content: '6 rings with 3 different coordinators says differently', timestamp: '2026-05-09T20:15:00Z' },
    ] as HotTakeComment[],
  },
];

export function getUserById(id: string): User | undefined {
  return USERS.find((u) => u.id === id);
}

export function getChatById(id: string): Chat | undefined {
  return CHATS.find((c) => c.id === id);
}

export function getTeamById(id: string): Team | undefined {
  return TEAMS.find((t) => t.id === id);
}
