// ESPN CDN logo mapping. URL format:
// https://a.espncdn.com/i/teamlogos/{league}/500/{abbrev}.png

const ESPN: Record<string, [league: string, abbrev: string]> = {
  // ── NFL ──────────────────────────────────────────────────────────────────
  giants:       ['nfl', 'nyg'],
  chiefs:       ['nfl', 'kc'],
  eagles:       ['nfl', 'phi'],
  cowboys:      ['nfl', 'dal'],
  niners:       ['nfl', 'sf'],
  bills:        ['nfl', 'buf'],
  dolphins:     ['nfl', 'mia'],
  patriots:     ['nfl', 'ne'],
  'ny-jets':    ['nfl', 'nyj'],
  ravens:       ['nfl', 'bal'],
  bengals:      ['nfl', 'cin'],
  browns:       ['nfl', 'cle'],
  steelers:     ['nfl', 'pit'],
  texans:       ['nfl', 'hou'],
  colts:        ['nfl', 'ind'],
  jaguars:      ['nfl', 'jax'],
  titans:       ['nfl', 'ten'],
  broncos:      ['nfl', 'den'],
  raiders:      ['nfl', 'lv'],
  chargers:     ['nfl', 'lac'],
  commanders:   ['nfl', 'wsh'],
  bears:        ['nfl', 'chi'],
  lions:        ['nfl', 'det'],
  packers:      ['nfl', 'gb'],
  vikings:      ['nfl', 'min'],
  falcons:      ['nfl', 'atl'],
  panthers:     ['nfl', 'car'],
  saints:       ['nfl', 'no'],
  buccaneers:   ['nfl', 'tb'],
  'az-cardinals': ['nfl', 'ari'],
  rams:         ['nfl', 'lar'],
  seahawks:     ['nfl', 'sea'],

  // ── NBA ──────────────────────────────────────────────────────────────────
  knicks:       ['nba', 'ny'],
  warriors:     ['nba', 'gs'],
  lakers:       ['nba', 'lal'],
  sixers:       ['nba', 'phi'],
  mavs:         ['nba', 'dal'],
  celtics:      ['nba', 'bos'],
  nets:         ['nba', 'bkn'],
  raptors:      ['nba', 'tor'],
  bulls:        ['nba', 'chi'],
  cavaliers:    ['nba', 'cle'],
  pistons:      ['nba', 'det'],
  pacers:       ['nba', 'ind'],
  bucks:        ['nba', 'mil'],
  hawks:        ['nba', 'atl'],
  hornets:      ['nba', 'cha'],
  heat:         ['nba', 'mia'],
  magic:        ['nba', 'orl'],
  wizards:      ['nba', 'wsh'],
  nuggets:      ['nba', 'den'],
  timberwolves: ['nba', 'min'],
  thunder:      ['nba', 'okc'],
  blazers:      ['nba', 'por'],
  jazz:         ['nba', 'utah'],
  clippers:     ['nba', 'lac'],
  suns:         ['nba', 'phx'],
  kings:        ['nba', 'sac'],
  rockets:      ['nba', 'hou'],
  grizzlies:    ['nba', 'mem'],
  pelicans:     ['nba', 'no'],
  spurs:        ['nba', 'sa'],

  // ── MLB ──────────────────────────────────────────────────────────────────
  yankees:        ['mlb', 'nyy'],
  'red-sox':      ['mlb', 'bos'],
  'blue-jays':    ['mlb', 'tor'],
  orioles:        ['mlb', 'bal'],
  rays:           ['mlb', 'tb'],
  'white-sox':    ['mlb', 'chw'],
  guardians:      ['mlb', 'cle'],
  tigers:         ['mlb', 'det'],
  royals:         ['mlb', 'kc'],
  twins:          ['mlb', 'min'],
  astros:         ['mlb', 'hou'],
  angels:         ['mlb', 'laa'],
  athletics:      ['mlb', 'oak'],
  mariners:       ['mlb', 'sea'],
  'tex-rangers':  ['mlb', 'tex'],
  braves:         ['mlb', 'atl'],
  marlins:        ['mlb', 'mia'],
  mets:           ['mlb', 'nym'],
  phillies:       ['mlb', 'phi'],
  nationals:      ['mlb', 'wsh'],
  cubs:           ['mlb', 'chc'],
  reds:           ['mlb', 'cin'],
  brewers:        ['mlb', 'mil'],
  pirates:        ['mlb', 'pit'],
  'stl-cardinals':['mlb', 'stl'],
  diamondbacks:   ['mlb', 'ari'],
  rockies:        ['mlb', 'col'],
  dodgers:        ['mlb', 'lad'],
  padres:         ['mlb', 'sd'],
  'sf-giants':    ['mlb', 'sf'],

  // ── NHL ──────────────────────────────────────────────────────────────────
  bruins:         ['nhl', 'bos'],
  sabres:         ['nhl', 'buf'],
  'red-wings':    ['nhl', 'det'],
  'fla-panthers': ['nhl', 'fla'],
  canadiens:      ['nhl', 'mtl'],
  senators:       ['nhl', 'ott'],
  lightning:      ['nhl', 'tb'],
  'maple-leafs':  ['nhl', 'tor'],
  rangers:        ['nhl', 'nyr'],
  hurricanes:     ['nhl', 'car'],
  'blue-jackets': ['nhl', 'cbj'],
  devils:         ['nhl', 'nj'],
  islanders:      ['nhl', 'nyi'],
  flyers:         ['nhl', 'phi'],
  penguins:       ['nhl', 'pit'],
  capitals:       ['nhl', 'wsh'],
  blackhawks:     ['nhl', 'chi'],
  avalanche:      ['nhl', 'col'],
  stars:          ['nhl', 'dal'],
  wild:           ['nhl', 'min'],
  predators:      ['nhl', 'nsh'],
  blues:          ['nhl', 'stl'],
  'wpg-jets':     ['nhl', 'wpg'],
  'utah-hc':      ['nhl', 'utah'],
  ducks:          ['nhl', 'ana'],
  flames:         ['nhl', 'cgy'],
  oilers:         ['nhl', 'edm'],
  'la-kings':     ['nhl', 'lak'],
  sharks:         ['nhl', 'sjs'],
  kraken:         ['nhl', 'sea'],
  canucks:        ['nhl', 'van'],
  'golden-knights':['nhl', 'vgk'],
};

export function getTeamLogoUrl(teamId: string): string | null {
  const entry = ESPN[teamId];
  if (!entry) return null;
  return `https://a.espncdn.com/i/teamlogos/${entry[0]}/500/${entry[1]}.png`;
}
